services:
  leaderboard:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_ADDR=redis:6379
    networks:
      - internal

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - internal

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - internal

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_LOG_LEVEL=error
    depends_on:
      - prometheus
    networks:
      - internal

networks:
  internal:
